export const CategoryData = [
  {id: 1,gerne: "액션",image: "image",},
  {id: 2,gerne: "아케이드",image: "image",},
  { id: 3, gerne: "리듬", image: "image" },
  { id: 4, gerne: "어드벤처", image: "image" },
  { id: 5, gerne: "RPG", image: "image" },
  { id: 6, gerne: "캐주얼", image: "image" },
  { id: 7, gerne: "매트로베니아", image: "image" },
  { id: 8, gerne: "퍼즐", image: "image" },
  { id: 9, gerne: "비주얼 노벨", image: "image" },
  { id: 10, gerne: "시뮬레이션", image: "image" },
  { id: 11, gerne: "전략", image: "image" },
  { id: 12, gerne: "카드게임", image: "image" },
  { id: 13, gerne: "보드게임", image: "image" },
  { id: 14, gerne: "도시", image: "image" },
];
